name: Build → Push → Run GHCR Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_name: ${{ steps.vars.outputs.image_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set lowercase image name and repo URL
      id: vars
      run: |
        IMAGE_NAME="ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]'):latest"
        REPO_URL="https://github.com/${{ github.repository }}"
        echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT

    - name: Write Dockerfile inline
      run: |
        cat <<EOF > Dockerfile
        FROM alpine:latest
        LABEL org.opencontainers.image.source="${{ steps.vars.outputs.repo_url }}"
        CMD ["echo", "Hello from the container run step!"]
        EOF

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ steps.vars.outputs.image_name }} .

    - name: Push Docker image
      run: docker push ${{ steps.vars.outputs.image_name }}

  run-container:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Pull and run container
      run: |
        IMAGE=${{ needs.build-and-push.outputs.image_name }}
        docker pull $IMAGE
        docker run --rm $IMAGE
