name: Build and Push to GHCR (Manual Dispatch, Inline Dockerfile)

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Write Dockerfile inline
      run: |
        cat <<EOF > Dockerfile
        FROM alpine:latest
        CMD ["echo", "Hello from a minimal image!"]
        EOF

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
        docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
        docker push $IMAGE_NAME
